version: '3.1'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asd123!@#
      MYSQL_DATABASE: caro_db
      MYSQL_USER: caro_user
      MYSQL_PASSWORD: caro_password